schema_version = 1
id = "hlsl-ls"
name = "HLSL Language Server"
description = "A language server for HLSL using Shader Language Server"
version = "0.1.0"
authors = ["Christian Howe <christianjacobhowe@gmail.com>"]
repository = "https://github.com/cjhowe-us/zed-hlsl-ls"

[language_servers.shader-language-server]
name = "Shader Language Server"
languages = ["HLSL"]
